SELECT * FROM NOTICES;

SELECT * FROM NOTICES ORDER BY REGDATE DESC ; 
--�Խñ� ��ȸ
SELECT ROWNUM FROM NOTICES;

--공지사항에서 가장 큰 코드값을 얻어어 오시오.
SELECT NVL(MAX(TO_NUMBER(CODE)),0)+1 FROM NOTICES ;

DELETE NOTICES WHERE CODE='129';

--20���� ���� ���ڵ带 ������ ������ �ۼ��Ͻÿ�.
--1������ / 2������

SELECT *FROM NOTICES ORDER BY REGDATE DESC;

SELECT *FROM (SELECT ROWNUM NUM, NO.* FROM (SELECT * FROM NOTICES ORDER BY REGDATE DESC) NO) WHERE NUM BETWEEN 11 AND 20



INSERT INTO NOTICES(CODE,TITLE,WRITER,CONTENT,REGDATE,HIT) VALUES('151','�Ѱf��','��ƼǮ������','�� ���� �Ѥ�',SYSDATE,444)


SELECT COUNT(*) CNT FROM NOTICES

SELECT (ROW_NUMBER() OVER (ORDER BY REGDATE DESC)) NUM , NOTICES.*
FROM NOTICES;

SELECT * FROM NOTICEFILES;

SELECT CAST(CODE AS INT)+1 AS CODE FROM NOTICEFILES;

SELECT ISNULL(MAX(CAST(CODE AS INT)),0)+1 FROM NOTICEFILES;

SELECT N.* FROM
(
SELECT (ROW_NUMBER() OVER (ORDER BY REGDATE DESC)) NUM , NOTICES.*
FROM NOTICES
) N
WHERE N.NUM BETWEEN 11 AND 20;

//이전글
SELECT TOP 1 * FROM NOTICES
WHERE REGDATE > (SELECT REGDATE FROM NOTICES WHERE CODE='242') 
ORDER BY REGDATE ASC;

//다음글
SELECT TOP 1 * FROM NOTICES
WHERE REGDATE < (SELECT REGDATE FROM NOTICES WHERE CODE='242') 
ORDER BY REGDATE DESC;

select * from members;

INSERT INTO MEMBERS (MID,NAME,PWD,NICNAME, CELLPHONE, EMAIL, ADDRESS)
                VALUES ('SUNGWAN','KIMSUNGWAN','12345','건배','010-6808-5036','pagedewn@naver.com','인천 연수구')
